/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconTablerBrandJavascript: typeof import('~icons/tabler/brand-javascript.svelte')['default']
  const IconTablerBrandVue: typeof import('~icons/tabler/brand-vue.svelte')['default']
  const IconTablerBrowser: typeof import('~icons/tabler/browser.svelte')['default']
  const IconTablerCloudComputing: typeof import('~icons/tabler/cloud-computing.svelte')['default']
  const IconTablerDeviceDesktop: typeof import('~icons/tabler/device-desktop.svelte')['default']
  const IconTablerHome: typeof import('~icons/tabler/home.svelte')['default']
  const IconTablerMail: typeof import('~icons/tabler/mail.svelte')['default']
  const IconTablerMenu: typeof import('~icons/tabler/menu.svelte')['default']
  const IconTablerMessage2: typeof import('~icons/tabler/message2.svelte')['default']
  const IconTablerNotebook: typeof import('~icons/tabler/notebook.svelte')['default']
  const IconTablerPackage: typeof import('~icons/tabler/package.svelte')['default']
  const IconTablerUser: typeof import('~icons/tabler/user.svelte')['default']
  const IconTablerVideo: typeof import('~icons/tabler/video.svelte')['default']
}
